version: '3.8'

services:
  # loadbalancer:
  #   build: .
  #   ports:
  #     - 5010:5010
  
  loadbalancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5010:5010

networks:
  default:
    external:
      name: bachelor-local